# Generated by Django 4.1 on 2023-09-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "seq_user_id",
                    models.BigAutoField(
                        db_column="SEQ_USER_ID",
                        help_text="ユーザID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        db_column="PASSWORD", help_text="パスワード", max_length=64
                    ),
                ),
                (
                    "company_cd",
                    models.CharField(
                        db_column="COMPANY_CD", help_text="企業コード", max_length=5
                    ),
                ),
                (
                    "reg_date",
                    models.DateTimeField(
                        auto_now_add=True, db_column="REG_DATE", help_text="登録日時"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, db_column="UPDATE_DATE", help_text="更新日時"
                    ),
                ),
            ],
            options={
                "db_table": "USER_DATA",
            },
        ),
    ]
