# Generated by Django 3.0.3 on 2023-09-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUserWorkData',
            fields=[
                ('daily_user_work_data_id', models.BigAutoField(help_text='日別ユーザ勤怠情報ID', primary_key=True, serialize=False)),
                ('seq_user_id', models.BigIntegerField(help_text='ユーザID')),
                ('company_code', models.CharField(help_text='企業コード', max_length=5)),
                ('work_data_reg_date', models.DateTimeField(auto_now_add=True, help_text='勤怠情報登録日時')),
                ('work_start_date', models.CharField(help_text='始業時刻', max_length=4)),
                ('work_end_date', models.CharField(help_text='終業時刻', max_length=4)),
                ('actual_work_date', models.CharField(help_text='実労働時間', max_length=4)),
                ('reg_date', models.DateTimeField(auto_now_add=True, help_text='登録日時')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('seq_user_id', models.BigAutoField(help_text='ユーザID', primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='パスワード', max_length=64)),
                ('company_code', models.CharField(help_text='企業コード', max_length=5)),
                ('reg_date', models.DateTimeField(auto_now_add=True, help_text='登録日時')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新日時')),
            ],
        ),
    ]
