# Generated by Django 4.1 on 2023-10-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kintai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDataHist",
            fields=[
                (
                    "seq_user_data_hist_id",
                    models.BigAutoField(
                        db_column="SEQ_USER_DATA_HIST_ID",
                        help_text="ユーザID情報履歴ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "seq_user_id",
                    models.BigIntegerField(db_column="SEQ_USER_ID", help_text="ユーザID"),
                ),
                (
                    "password",
                    models.CharField(
                        db_column="PASSWORD", help_text="パスワード", max_length=64
                    ),
                ),
                (
                    "company_cd",
                    models.CharField(
                        db_column="COMPANY_CD", help_text="企業コード", max_length=5
                    ),
                ),
                (
                    "division_cd",
                    models.CharField(
                        db_column="DIVISION_CD",
                        default="",
                        help_text="部署コード",
                        max_length=5,
                    ),
                ),
                (
                    "del_flg",
                    models.BooleanField(
                        db_column="DEL_FLG",
                        default=False,
                        help_text="削除フラグ",
                        max_length=5,
                    ),
                ),
                (
                    "reg_date",
                    models.DateTimeField(
                        auto_now_add=True, db_column="REG_DATE", help_text="登録日時"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, db_column="UPDATE_DATE", help_text="更新日時"
                    ),
                ),
            ],
            options={
                "db_table": "USER_DATA_HIST",
            },
        ),
    ]
