# Generated by Django 4.1 on 2023-09-11 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kintai", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailyuserworkdata",
            old_name="company_code",
            new_name="company_cd",
        ),
        migrations.RenameField(
            model_name="userdata",
            old_name="company_code",
            new_name="company_cd",
        ),
        migrations.AlterModelTable(
            name="dailyuserworkdata",
            table="DAILY_USER_WORK_DATA",
        ),
        migrations.AlterModelTable(
            name="userdata",
            table="USER_DATA",
        ),
    ]
