# Generated by Django 4.1 on 2023-10-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kintai", "0002_userdatahist"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestTimeMt",
            fields=[
                (
                    "seq_rest_time_mt_id",
                    models.BigAutoField(
                        db_column="SEQ_REST_TIME_MT_ID",
                        help_text="休憩時間マスタID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company_cd",
                    models.CharField(
                        db_column="COMPANY_CD",
                        default="",
                        help_text="企業コード",
                        max_length=5,
                    ),
                ),
                (
                    "division_cd",
                    models.CharField(
                        db_column="DIVISION_CD",
                        default="",
                        help_text="部署コード",
                        max_length=5,
                    ),
                ),
                (
                    "start_hour",
                    models.CharField(
                        db_column="START_HOUR", help_text="休憩開始時間(時)", max_length=4
                    ),
                ),
                (
                    "start_minute",
                    models.CharField(
                        db_column="START_MINUTE", help_text="休憩開始時間(分)", max_length=4
                    ),
                ),
                (
                    "end_hour",
                    models.CharField(
                        db_column="END_HOUR", help_text="休憩終了時間(時)", max_length=4
                    ),
                ),
                (
                    "end_minute",
                    models.CharField(
                        db_column="END_MINUTE", help_text="休憩終了時間(分)", max_length=4
                    ),
                ),
                (
                    "del_flg",
                    models.BooleanField(
                        db_column="DEL_FLG", default=False, help_text="削除フラグ"
                    ),
                ),
                (
                    "reg_date",
                    models.DateTimeField(
                        auto_now_add=True, db_column="REG_DATE", help_text="登録日時"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, db_column="UPDATE_DATE", help_text="更新日時"
                    ),
                ),
            ],
            options={
                "db_table": "REST_TIME_MT",
            },
        ),
        migrations.AlterField(
            model_name="ontimemt",
            name="seq_ontime_mt_id",
            field=models.BigAutoField(
                db_column="SEQ_ONTIME_MT_ID",
                help_text="定時マスタID",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="resttimemt",
            constraint=models.UniqueConstraint(
                fields=("company_cd", "division_cd"), name="unique_rest_time_mt"
            ),
        ),
    ]
