# Generated by Django 4.1 on 2023-09-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kintai", "0002_companymt_dailyuserworkdata_divisionmt_ontimemt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyuserworkdata",
            name="division_cd",
            field=models.CharField(
                db_column="DIVISION_CD", default="", help_text="部署コード", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="userdata",
            name="division_cd",
            field=models.CharField(
                db_column="DIVISION_CD", default="", help_text="部署コード", max_length=5
            ),
        ),
        migrations.AlterField(
            model_name="ontimemt",
            name="division_cd",
            field=models.CharField(
                db_column="DIVISION_CD", default="", help_text="部署コード", max_length=5
            ),
        ),
    ]
