# Generated by Django 4.1 on 2023-09-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kintai", "0003_dailyuserworkdata_division_cd_userdata_division_cd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companymt",
            name="del_flg",
            field=models.BooleanField(
                db_column="DEL_FLG", default=False, help_text="削除フラグ", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="divisionmt",
            name="del_flg",
            field=models.BooleanField(
                db_column="DEL_FLG", default=False, help_text="削除フラグ", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="ontimemt",
            name="del_flg",
            field=models.BooleanField(
                db_column="DEL_FLG", default=False, help_text="削除フラグ", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="userdata",
            name="del_flg",
            field=models.BooleanField(
                db_column="DEL_FLG", default=False, help_text="削除フラグ", max_length=5
            ),
        ),
    ]
