# Generated by Django 4.1 on 2023-10-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kintai", "0004_delete_resttimemt"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyuserworkdata",
            name="rest_time",
            field=models.DecimalField(
                db_column="REST_TIME",
                decimal_places=2,
                default=0.0,
                help_text="休憩時間",
                max_digits=2,
            ),
        ),
    ]
