# Generated by Django 4.1 on 2023-09-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kintai", "0004_companymt_del_flg_divisionmt_del_flg_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessCalendarMt",
            fields=[
                (
                    "seqBusinessCalendarMtId",
                    models.BigAutoField(
                        db_column="SEQ_BUSINESS_CALENDAR_MT_ID",
                        help_text="営業日マスタID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_column="DATE", help_text="日付")),
                (
                    "weekday",
                    models.CharField(db_column="WEEKDAY", help_text="曜日", max_length=4),
                ),
                (
                    "business_flg",
                    models.BooleanField(
                        db_column="BUSINESS_FLG", default=True, help_text="営業日フラグ"
                    ),
                ),
                (
                    "reg_date",
                    models.DateTimeField(
                        auto_now_add=True, db_column="REG_DATE", help_text="登録日時"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(
                        auto_now=True, db_column="UPDATE_DATE", help_text="更新日時"
                    ),
                ),
            ],
            options={
                "db_table": "BUSINESS_CALENDAR_MT",
            },
        ),
    ]
