# Generated by Django 4.1 on 2023-09-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "kintai",
            "0006_rename_seqbusinesscalendarmtid_businesscalendarmt_seq_business_calendar_mt_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyuserworkdata",
            name="work_end_date",
            field=models.DateTimeField(db_column="WORK_END_DATE", help_text="終業時刻"),
        ),
        migrations.AlterField(
            model_name="dailyuserworkdata",
            name="work_start_date",
            field=models.DateTimeField(db_column="WORK_START_DATE", help_text="始業時刻"),
        ),
    ]
