# Generated by Django 4.1 on 2023-10-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kintai", "0006_alter_dailyuserworkdata_rest_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyuserworkdata",
            name="actual_work_date",
            field=models.DecimalField(
                db_column="ACTUAL_WORK_TIME",
                decimal_places=2,
                help_text="実労働時間",
                max_digits=4,
            ),
        ),
    ]
