# Generated by Django 4.1 on 2023-10-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kintai", "0007_alter_dailyuserworkdata_actual_work_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyuserworkdata",
            name="over_time",
            field=models.DecimalField(
                db_column="OVER_TIME",
                decimal_places=2,
                help_text="残業時間",
                max_digits=4,
                null=True,
            ),
        ),
    ]
