# Generated by Django 4.1 on 2023-09-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kintai", "0007_alter_dailyuserworkdata_work_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyworkDto",
            fields=[
                (
                    "businesscalendarmt_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="kintai.businesscalendarmt",
                    ),
                ),
            ],
            bases=("kintai.businesscalendarmt",),
        ),
        migrations.AddField(
            model_name="dailyuserworkdata",
            name="approval_flg",
            field=models.BooleanField(
                db_column="APPROVAL_FLG", default=False, help_text="承認フラグ"
            ),
        ),
        migrations.AddField(
            model_name="dailyuserworkdata",
            name="cancel_flg",
            field=models.BooleanField(
                db_column="CANCEL_FLG", default=False, help_text="取消申請フラグ"
            ),
        ),
        migrations.AlterField(
            model_name="ontimemt",
            name="del_flg",
            field=models.BooleanField(
                db_column="DEL_FLG", default=False, help_text="削除フラグ"
            ),
        ),
    ]
