# Generated by Django 4.1 on 2023-09-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kintai", "0008_dailyworkdto_dailyuserworkdata_approval_flg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companymt",
            name="del_flg",
            field=models.BooleanField(
                db_column="DEL_FLG", default=False, help_text="削除フラグ"
            ),
        ),
        migrations.AlterField(
            model_name="divisionmt",
            name="del_flg",
            field=models.BooleanField(
                db_column="DEL_FLG", default=False, help_text="削除フラグ"
            ),
        ),
    ]
