# Generated by Django 4.1 on 2023-10-01 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0009_alter_companymt_del_flg_alter_divisionmt_del_flg'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCalendarMtDto',
            fields=[
                ('businesscalendarmt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kintai.businesscalendarmt')),
            ],
            bases=('kintai.businesscalendarmt',),
        ),
        migrations.CreateModel(
            name='CompanyMtDto',
            fields=[
                ('companymt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kintai.companymt')),
            ],
            bases=('kintai.companymt',),
        ),
        migrations.CreateModel(
            name='DailyUserWorkDataDto',
            fields=[
                ('dailyuserworkdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kintai.dailyuserworkdata')),
            ],
            bases=('kintai.dailyuserworkdata',),
        ),
        migrations.CreateModel(
            name='DivisionMtDto',
            fields=[
                ('divisionmt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kintai.divisionmt')),
            ],
            bases=('kintai.divisionmt',),
        ),
        migrations.CreateModel(
            name='UserDataDto',
            fields=[
                ('userdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kintai.userdata')),
            ],
            bases=('kintai.userdata',),
        ),
        migrations.AddField(
            model_name='dailyuserworkdata',
            name='note',
            field=models.CharField(db_column='NOTE', help_text='備考', max_length=128, null=True),
        ),
    ]
