# Generated by Django 4.1 on 2023-10-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kintai', '0010_businesscalendarmtdto_companymtdto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymtdto',
            name='companymt_ptr',
        ),
        migrations.RemoveField(
            model_name='dailyuserworkdatadto',
            name='dailyuserworkdata_ptr',
        ),
        migrations.RemoveField(
            model_name='dailyworkdto',
            name='businesscalendarmt_ptr',
        ),
        migrations.RemoveField(
            model_name='divisionmtdto',
            name='divisionmt_ptr',
        ),
        migrations.RemoveField(
            model_name='userdatadto',
            name='userdata_ptr',
        ),
        migrations.DeleteModel(
            name='BusinessCalendarMtDto',
        ),
        migrations.DeleteModel(
            name='CompanyMtDto',
        ),
        migrations.DeleteModel(
            name='DailyUserWorkDataDto',
        ),
        migrations.DeleteModel(
            name='DailyworkDto',
        ),
        migrations.DeleteModel(
            name='DivisionMtDto',
        ),
        migrations.DeleteModel(
            name='UserDataDto',
        ),
    ]
